# Report Templates Configuration
invoice:
  logo:
    path: "${INVOICE_LOGO_PATH:/jasper/images/LOGO.png}"
  template:
    path: "${INVOICE_TEMPLATE_PATH:/jasper/Facturas.jrxml}"
recibo:
  template:
    path: "${RECIBO_TEMPLATE_PATH:/jasper/Recibos.jrxml}"
orden:
  template:
    path: "${ORDEN_TEMPLATE_PATH:/jasper/OrdenServicio.jrxml}"
spring:
  logging:
    file:
      name: ./sysred.log
    level:
      root: INFO
  # Thymeleaf Configuration
  thymeleaf:
    mode: HTML
    cache: true
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://74.208.118.100/sysred2023?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: camiloleal
    password: C4m1l02020+-+
    hikari:
      connection-test-query: "SELECT 1 FROM DUAL"
      connection-timeout: 20000
      maximum-pool-size: 50
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none    # Changed for production safety
    open-in-view: true # Performance improvement
    show-sql: false     # Disable SQL logging in production
  mail:
    host: smtp.gmail.com
    port: 587
    username: sysredcartagena@gmail.com
    password: zuusiizspvvzjcgb
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
factura:
  path: "${PATH_FACTURAS:/var/www/html/facturas/}"
message :
  urlChat: "https://www.wasenderapi.com/api/send-message"
  urlDocument : "https://www.wasenderapi.com/api/send-message"
  uriWhatsappApiSender: "https://www.wasenderapi.com/api/send-message"
  tokenBearerWhatsappApiSender: "Bearer 53d2b099e4caa7a4aac7941bbe0b843918d68ea86ec53127bb676608d38b2a20"
  msgToken : "TOKEN:hjfsf"
server:
  port: ${PORT:8889}
  tomcat:
    max-threads: 200
    min-spare-threads: 20
  compression:
    enabled: true
    min-response-size: 1024
sysred :
  notification :
    cron : "${CRON_SCHEDULED:0 0 9 * * 2,6}"
